### ISSUE TITLE
ipad中报错nan错误

### ISSUE THREAD

**Issue by black1997** [k373379320/ZBImageText#1]
<img width="804" alt="WX20190409-160904@2x" src="https://user-images.githubusercontent.com/15035749/55783839-e8b79e80-5ae1-11e9-86a1-a76e434f880f.png">

**Comment by k373379320** [comment]
确认下 font 有无问题,或者你把你写的代码发出来我测试跟进下

**Comment by k373379320** [comment]
使用pod update, 已经更新容错代码;

**Comment by black1997** [comment]
收到、谢谢

**Comment by k373379320** [comment]
UIEdgeInsets borderMargin = UIEdgeInsetsZero;
没有设置UIEdgeInsetsZero导致的
